### ISSUE TITLE
No notification in Centos7

### ISSUE THREAD

**Issue by xidabei** [BillBillBillBill/Tickeys-linux#19]
Thanks for your software, it's very interesting.
My distribution is Centos7, and I can install and use Tickeys, but there will be an error when start the software. Something like about the notification. 
 The error as followed:
org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/tickeys/GUI.py", line 203, in show_notify
    notify2.init('Tickeys')
  File "/usr/lib/python2.7/site-packages/notify2.py", line 96, in init
    '/org/freedesktop/Notifications')
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 241, in get_object
    follow_name_owner_changes=follow_name_owner_changes)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 248, in **init**
    self._named_service = conn.activate_name_owner(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 180, in activate_name_owner
    self.start_service_by_name(bus_name)
  File "/usr/lib/python2.7/site-packages/dbus/bus.py", line 278, in start_service_by_name
    'su', (bus_name, flags)))
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
# show notify fail

I try to create a new file at /usr/share/dbus-1/service called org.freedesktop.Notification.service, the content of the file is
[D-BUS Service]
Name=org.freedesktop.Notifications
Exec=/usr/bin/notify-send

It still failed, and i got another error about notify-send. Thanks a lot.

**Comment by BillBillBillBill** [comment]
看来作者挺困扰的:[https://bitbucket.org/takluyver/pynotify2/issues/3/dbusexceptionsdbusexception](https://bitbucket.org/takluyver/pynotify2/issues/3/dbusexceptionsdbusexception)
