### ISSUE TITLE
一直在用，很有黑客的感觉

### ISSUE THREAD

**Issue by wcx1978** [BillBillBillBill/Tickeys-linux#20]
一直在用，很有黑客的感觉。
大力支持您。

请问在 debian 下，kali 2 linux 安装都好像出问题。
有没有在 arm cpu上 arm hf 版的。我用在树莓派上。

谢谢

**Comment by BillBillBillBill** [comment]
谢谢　有详细报错信息吗？

**Comment by wcx1978** [comment]
normal@kali:/media/normal/SETLINUX/Downloads/tickeys$ sudo dpkg -i tickeys_0.2.4_amd64.deb
[sudo] normal 的密码：
正在选中未选择的软件包 tickeys。
(正在读取数据库 ... 系统当前共安装有 318840 个文件和目录。)
正准备解包 tickeys_0.2.4_amd64.deb  ...
正在解包 tickeys (0.2.4) ...
正在设置 tickeys (0.2.4) ...
正在处理用于 gnome-menus (3.13.3-8) 的触发器 ...
正在处理用于 desktop-file-utils (0.23-1) 的触发器 ...
正在处理用于 mime-support (3.60) 的触发器 ...
normal@kali:/media/normal/SETLINUX/Downloads/tickeys$ tickeys
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/home/bill/Desktop/github/Tickeys-linux/tickeys/logger.py", line 14, in <module>
  File "/usr/lib/python2.7/logging/**init**.py", line 905, in **init**
    self.encoding = encoding
  File "/usr/lib/python2.7/logging/**init**.py", line 935, in _open
    self.release()
IOError: [Errno 13] Permission denied: '/tmp/tickeys.log'
run returned -1
双击图标能启动。  
那2.5 python版的不好装。 建议还是弄成deb 包。 用 dpkg -i 安装才好推广。  python3.0我也在用。各人机器配置起来复杂。弄成一通用包好。
