### ISSUE TITLE
tickeys2.4在kali2中安装出问题

### ISSUE THREAD

**Issue by wcx1978** [BillBillBillBill/Tickeys-linux#22]
root@kali:/home/normal/下载# dpkg -i tickeys_0.2.4_amd64.deb
(正在读取数据库 ... 系统当前共安装有 321919 个文件和目录。)
正准备解包 tickeys_0.2.4_amd64.deb  ...
正在将 tickeys (0.2.4) 解包到 (0.2.4) 上 ...
正在设置 tickeys (0.2.4) ...
正在处理用于 gnome-menus (3.13.3-8) 的触发器 ...
正在处理用于 desktop-file-utils (0.23-1) 的触发器 ...
正在处理用于 mime-support (3.60) 的触发器 ...
正在处理用于 menu (2.1.47) 的触发器 ...
－－－－－－－－－－－－－－－－－－－－－－－－－－
＃  装完后图标找不到，于是用命令看看。
root@kali:/home/normal/下载# tickeys
bash: tickeys: 未找到命令
＃ 换用 python 来装
－－－－－－－－－－－－－－－－－－
root@kali:/home/normal/下载# pip install tickeys
Collecting tickeys
  Downloading tickeys-0.2.5.tar.gz (5.3MB)
    100% |████████████████████████████████| 5.3MB 37kB/s 
Collecting cython==0.20.2 (from tickeys)
  Downloading Cython-0.20.2-cp27-cp27mu-manylinux1_x86_64.whl (4.9MB)
    100% |████████████████████████████████| 4.9MB 95kB/s 
Collecting kivy==1.9.0 (from tickeys)
  Downloading Kivy-1.9.0.tar.gz (16.2MB)
    100% |████████████████████████████████| 16.2MB 31kB/s 
    Complete output from command python setup.py egg_info:
    Cython is missing, its required for compiling kivy !
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-dMkiOB/kivy/setup.py", line 173, in <module>
        from Cython.Distutils import build_ext
    ImportError: No module named Cython.Distutils
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-dMkiOB/kivy/
root@kali:/home/normal/下载# 
------------------------------
于是，我用synaptic 把tickeys卸了再重装

root@kali:/home/normal/下载# dpkg -i tickeys_0.2.4_amd64.deb
正在选中未选择的软件包 tickeys。
(正在读取数据库 ... 系统当前共安装有 321908 个文件和目录。)
正准备解包 tickeys_0.2.4_amd64.deb  ...
正在解包 tickeys (0.2.4) ...
正在设置 tickeys (0.2.4) ...
正在处理用于 gnome-menus (3.13.3-8) 的触发器 ...
正在处理用于 desktop-file-utils (0.23-1) 的触发器 ...
正在处理用于 mime-support (3.60) 的触发器 ...
root@kali:/home/normal/下载# tickeys
[Errno 2] No such file or directory: '/tmp/tickeys_GUI_window_id'
Root checking...
Root checking success. You have the root permission
System checking...
System checking success. Your system is supported
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_16-11-11_4.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.11 (default, Jan 11 2016, 21:04:40) 
[GCC 5.3.1 20160101]
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  97
  Current serial number in output stream:  98
root@kali:/home/normal/下载# 
＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝＝
我在另一台笔记本电脑装又可以发声。请教。我这系统还少什么？
我是如下这样一步步装的
* sudo apt-get install python-dev python-kivy 安装依赖
* sudo apt-get install xdotool 解决无法隐藏窗口问题
* sudo apt-get install libsdl1.2-dev (已经是最新版 (1.2.15+dfsg1-4)。)
* sudo apt-get install libsdl-mixer1.2 (已经是最新版 (1.2.12-11+b1))
* sudo apt-get install libsdl-ttf2.0
最后：正式安装
从 https://github.com/BillBillBillBill/Tickeys-linux/releases
下载   tickeys_0.2.4_amd64.deb
dpkg -i tickeys_0.2.4_amd64.deb
pip install tickeys

**Comment by wcx1978** [comment]
# 后面怎么启动都报错

normal@kali:~/下载$ tickeys
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
  File "/home/bill/Desktop/github/Tickeys-linux/tickeys/logger.py", line 14, in <module>
  File "/usr/lib/python2.7/logging/**init**.py", line 905, in **init**
    self.encoding = encoding
  File "/usr/lib/python2.7/logging/**init**.py", line 935, in _open
    self.release()
IOError: [Errno 13] Permission denied: '/tmp/tickeys.log'
run returned -1
normal@kali:~/下载$ sudo tickeys
[Errno 2] No such file or directory: '/tmp/tickeys_GUI_window_id'
Root checking...
Root checking success. You have the root permission
System checking...
System checking success. Your system is supported
[INFO   ] [Logger      ] Record log in /root/.kivy/logs/kivy_16-11-11_7.txt
[INFO   ] [Kivy        ] v1.9.0
[INFO   ] [Python      ] v2.7.11 (default, Jan 11 2016, 21:04:40) 
[GCC 5.3.1 20160101]
[INFO   ] [Factory     ] 173 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [OSC         ] using <multiprocessing> for socket
[INFO   ] [Window      ] Provider: sdl2(['window_egl_rpi'] ignored)
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  97
  Current serial number in output stream:  98
normal@kali:~/下载$
