### ISSUE TITLE
在manjaro上pip安装报错

### ISSUE THREAD

**Issue by roachsinai** [BillBillBillBill/Tickeys-linux#34]
在manjaro上pip安装报如下错误：

```
roach@xq-pc  ~  sudo pip install tickeys                        
[sudo] roach 的密码：
Collecting tickeys
  Downloading https://files.pythonhosted.org/packages/42/55/0c3a0f0adf3d5b764f3b6a9031c9655e792fda09f0002ab72bf16a480a72/tickeys-0.2.5.tar.gz (5.3MB)
    100% |████████████████████████████████| 5.3MB 889kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vb36yxnl/tickeys/setup.py", line 2, in <module>
        from tickeys import __version__, __author__, __email__
      File "/tmp/pip-install-vb36yxnl/tickeys/tickeys/__init__.py", line 6, in <module>
        from run import main
    ModuleNotFoundError: No module named 'run'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-vb36yxnl/tickeys/
```

**Comment by bigshans** [comment]
出现同样的问题。
python 是 3.8 的。
