### ISSUE TITLE
installation: no module "run"

### ISSUE THREAD

**Issue by stardiviner** [BillBillBillBill/Tickeys-linux#4]
```
$ sudo pip install tickeys
Collecting tickeys
  Using cached tickeys-0.1.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-tig6dqhw/tickeys/setup.py", line 2, in <module>
        from tickeys import __version__, __author__, __email__
      File "/tmp/pip-build-tig6dqhw/tickeys/tickeys/__init__.py", line 5, in <module>
        from run import run
    ImportError: No module named 'run'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tig6dqhw/tickeys
```

Why?
Then I tried to install "run" with `pip install run`, but got another error:

```
 ⇨   pip install run                                                    1 ↵  Hack
Collecting run
  Using cached run-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-6ex44xsk/run/setup.py", line 12, in <module>
        long_description=file('README').read(),
    NameError: name 'file' is not defined

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-6ex44xsk/run
```

**Comment by BillBillBillBill** [comment]
It's weird. Try to use easy_install tickeys to install?

**Comment by stardiviner** [comment]
```
$ sudo easy_install tickeys
Searching for install
Reading https://pypi.python.org/simple/install/
Couldn't find index page for 'install' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for install
error: Could not find suitable distribution for Requirement.parse('install')
```

Seems can't find file on website, I thought it could be network problem, so I started proxy, but still same error.

**Comment by BillBillBillBill** [comment]
Did you use `sudo easy_install install tickeys`, not `sudo easy_install tickeys`
?

Then check your python version, whether it is version 2.7 or not.

It seems that you use the arch linux, I didn't test tickeys on it, sorry for that. :(

**Comment by stardiviner** [comment]
@BillBillBillBill sorry, I use `sudo easy_install install tickeys`, I paste from tmux, error formated.
Yes, I'm using Arch Linux, And using Python `3.4.3`. and `pip 7.1.2`, and `easy_install setup_tools 12.0.5`.

**Comment by BillBillBillBill** [comment]
Maybe you can try python2.7 then using  'sudo easy_install tickeys':)

**Comment by stardiviner** [comment]
Still does not work, same error. Can we keep this open? I will deal with this issue in some days.

**Comment by BillBillBillBill** [comment]
OK, thank you for the issue

**Comment by stardiviner** [comment]
Now, the command `sudo easy_install-2.7 tickeys` successed.
